Initial exception handling for Cache.flattenMaterials
The NullPointerException mentioned in (link) seems to be gone and though it is possible join and move around the world, the following error is repeatedly reported to console:

```
[pool-6-thread-15162/ERROR] (FabricLoader) Uncaught exception in thread "pool-6-thread-15162"
 java.lang.NullPointerException: Cannot invoke "dev.thedocruby.resounding.Material.equals(Object)" because "root.material" is null
	at dev.thedocruby.resounding.Cache.growOctree(Cache.java:116) ~[main/:?]
	at dev.thedocruby.resounding.Cache.growOctree(Cache.java:94) ~[main/:?]
	at dev.thedocruby.resounding.Cache.growOctree(Cache.java:94) ~[main/:?]
	at dev.thedocruby.resounding.Cache.growOctree(Cache.java:94) ~[main/:?]
	at dev.thedocruby.resounding.Cache.plantOctree(Cache.java:68) ~[main/:?]
	at net.minecraft.world.chunk.WorldChunk.md1b5fba$resounding$lambda$initStorage$0$1(WorldChunk.java:1351) ~[minecraft-merged-project-root-1.18.2-net.fabricmc.yarn.1_18_2.1.18.2+build.2-v2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```